### ISSUE TITLE
mp.createCardToken problem

### ISSUE THREAD

**Issue by Felipelpk** [mercadopago/sdk-js#43] opened 2021-12-20 04:30 UTC
Describe the bug
mp.createCardToken is giving me the following error:
{
code: "E601"
description: "an error occurred doing POST card_token"
}

To Reproduce
Just running the example:

const cardToken = await mp.createCardToken({
        cardNumber: '5031433215406351',
        cardholderName: 'APRO',
        cardExpirationMonth: '11',
        cardExpirationYear: '2025',
        securityCode: '123',
        identificationType: 'CPF',
        identificationNumber: '12345678912',
});

**Comment by lucmantovani** [comment] 2021-12-20 12:47
Hello @Felipelpk!

I could reproduce the error with the same parameters you suggested, but after some retries I was able to create some tokens.

As this is not a problem with this SDK, I will close this issue.
If you have any trouble that is not directly related to the SDK, I recommend to open a ticket [here](https://www.mercadopago.com.br/developers/pt/support/center/tickets)

You are welcome to open new issues should you have any other situation with the SDKs!

Have a nice day!

**Comment by lucmantovani** [comment] 2021-12-20 14:48
@Felipelpk, just a little bit of more information...

We were facing a temporary problem with the card_token API, but it should be normalized now.

**Comment by jonathan-easycodigo** [comment] 2021-12-21 01:49
I have the same problem, i get:

{"message":"an error occurred doing POST card_token","status":500,"error":"internal_error","cause":[{"description":"an error occurred doing POST card_token","code":"E603"}]}

When will normalized?

**Comment by Felipelpk** [comment] 2021-12-21 05:34
Hi guys, @jonathan-easycodigo @lucmantovani 
For me, it's working good at moment.

**Comment by jonathan-easycodigo** [comment] 2021-12-21 14:41
Hi @Felipelpk , i still have the problem.. can you share me some code to review it?

**Comment by Felipelpk** [comment] 2021-12-21 20:56
Hi @jonathan-easycodigo,

`const cardToken = await mpResponse.createCardToken({
            cardNumber: number,
            cardholderName: name,
            cardExpirationMonth: expireMonth,
            cardExpirationYear: expireYearFormatedd,
            securityCode: cvc,
            identificationType: isDocumentCPF ? "CPF" : "CNPJ",
            identificationNumber: userDocumentNumber,
        }).catch(err => {
            toast({
                title: "Ops...",
                description: `Verifique os dados do cartão e tente novamente`,
                status: "error",
                duration: 5000,
                isClosable: true,
            })
            setCreditLoading(false)
            return
        })`

**Comment by Felipelpk** [comment] 2021-12-21 21:03
Hi @jonathan-easycodigo,

> const cardToken = await mpResponse.createCardToken({
            cardNumber: number,
            cardholderName: name,
            cardExpirationMonth: expireMonth,
            cardExpirationYear: expireYearFormatedd,
            securityCode: cvc,
            identificationType: isDocumentCPF ? "CPF" : "CNPJ",
            identificationNumber: userDocumentNumber,
        }).catch(err => {
            toast({
                title: "Ops...",
                description: `Verifique os dados do cartão e tente novamente`,
                status: "error",
                duration: 5000,
                isClosable: true,
            })
            setCreditLoading(false)
            return
        })

**Comment by jonathan-easycodigo** [comment] 2021-12-22 18:00
Hi @Felipelpk i have my code equals to yours buy i still having this problem, sometimes works.. sometimes dont work.. i dont know if this is an temporal error or is a problem with my code...

**Comment by NicholasPedroso** [comment] 2021-12-28 12:51
Hello, how are you?
I tested it here and everything is fine.
We are working to verify the reason for this instability and as soon as we get some position, I'll come back here with you

@jonathan-easycodigo @Felipelpk Can you tell me if the instability still persists, please?

Thanks

**Comment by jonathan-easycodigo** [comment] 2021-12-28 19:38
Hi @NicholasPedroso, i dont know if the instability persists, i have pointing to production and works fine, only with test credentials had instability, i dont know why.. thanks

**Comment by NicholasPedroso** [comment] 2021-12-28 21:40
Hi @jonathan-easycodigo 

Oh yes, it's critical to say that this instability only occurs with **test credentials.**
As soon as I have an answer I'll let you know,

Thanks again

**Closed** 2022-01-08 23:02 UTC
